# ensure INTERFACE64 variable gets detected by conda-build
# [INTERFACE64 == "foobar"]
# [SYMBOLSUFFIX == "foobar"]
# [name_suffix == "foobar"]
schema_version: 1

context:
  version: "0.3.23"
  build_number: 0

recipe:
  name: openblas
  version: ${{ version }}

source:
  url: https://github.com/xianyi/OpenBLAS/archive/v${{ version }}.tar.gz
  sha256: 5d9491d07168a5d00116cdc068a40022c3455bf9293c7cb86a65b1054d7e5114

build:
  number: ${{ build_number }}
  string: ${{ 'pthreads_h${{ PKG_HASH }}_${{ build_number }}' if USE_OPENMP == 0 else 'openmp_h${{ PKG_HASH }}_${{ build_number }}' if USE_OPENMP == 1 else '' }}

outputs:
  - package:
      name: libopenblas${{ name_suffix }}
    build:
      string: ${{ 'pthreads_h${{ PKG_HASH }}_${{ build_number }}' if USE_OPENMP == 0 else 'openmp_h${{ PKG_HASH }}_${{ build_number }}' if USE_OPENMP == 1 else '' }}
      files:
        # Include files like
        #   - libopenblasp-r0.3.5.so
        #   - libopenblas_vortexp-r0.3.5.so
        #   - libopenblas.so.0
        # Avoid files
        #   - libopenblas.so
        - if: not win
          then: lib/libopenblas*p*
        - if: linux
          then: lib/libopenblas${{ SYMBOLSUFFIX }}.so.*
        - if: osx
          then: lib/libopenblas${{ SYMBOLSUFFIX }}.*.dylib
        - if: win
          then: Library/bin/openblas${{ SYMBOLSUFFIX }}.dll      
    requirements:
      build:
        - ${{ stdlib("c") }}
        - ${{ compiler("c") }}
        - ${{ compiler("fortran") }}
        - perl
        - if: not win
          then: make
        - if: win
          then: cmake
        - if: win
          then: curl
        - if: win
          then: jom
        - if: osx
          then: objconv
        - if: (osx or linux) and USE_OPENMP == 1
          then: llvm-openmp
        # Following is needed because the Fortran compiler add an rpath to the BUILD_PREFIX
        - if: linux and USE_OPENMP == 1
          then: _openmp_mutex * *_llvm
      run_exports:
        - ${{ pin_subpackage("libopenblas" ~ name_suffix) }}
    tests:
      - requirements:
          run:
            - python *
        script:
          - if: not win
            then: test -f ${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}${{ SHLIB_EXT }}
          - if: osx and build_platform=="osx-64"
            then: nm -g ${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}${{ SHLIB_EXT }} | grep dsecnd
          - if: not win
            then: python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}p-r${{ version }}${{ SHLIB_EXT }}']"
          - if: win
            then: if not exist %PREFIX%\\Library\\bin\\openblas${{ SYMBOLSUFFIX }}.dll exit 1
  - package:
      name: openblas${{ name_suffix }}
    build:
      string: ${{ 'pthreads_h${{ PKG_HASH }}_${{ build_number }}' if USE_OPENMP == 0 else 'openmp_h${{ PKG_HASH }}_${{ build_number }}' if USE_OPENMP == 1 else '' }}
      files:
        - if: not win
          then: include/*.h
        - if: not win
          then: lib/libopenblas${{ SYMBOLSUFFIX }}*.a
        - if: not win
          then: lib/libopenblas*
        - if: not win
          then: lib/pkgconfig/openblas.pc
        - if: not win
          then: lib/cmake/openblas/*
        - if: win
          then: Library/include/openblas
        - if: win
          then: Library/lib/openblas${{ SYMBOLSUFFIX }}.lib
        - if: win
          then: Library/lib/pkgconfig/openblas.pc
        - if: win
          then: Library/share/cmake/OpenBLAS
    requirements:
      run:
        - ${{ pin_subpackage("libopenblas" ~ name_suffix, exact=True) }}
    tests:
      - script:
          - if: not win
            then: test -f ${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}.a
          - if: not win
            then: test -f ${PREFIX}/lib/libopenblas${{ SYMBOLSUFFIX }}${{ SHLIB_EXT }}
          - if: win
            then: if not exist %PREFIX%\\Library\\lib\\openblas${{ SYMBOLSUFFIX }}.lib exit 1

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - lapack-netlib/LICENSE
  summary: ${{ 'An optimized BLAS library (ILP64 interface) based on GotoBLAS2 1.13 BSD version' if SYMBOLSUFFIX == "64_" else 'An optimized BLAS library based on GotoBLAS2 1.13 BSD version' if SYMBOLSUFFIX != "64_" else '' }}
  homepage: http://www.openblas.net/
  repository: https://github.com/xianyi/openblas

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - jakirkham
    - isuruf
    - h-vetinari

