# as of LLVM 19, we expect an "-rcX" suffix for the release candidates
schema_version: 1

context:
  version: "21.1.8"
  major_version: "21"
  tail_version: "8"
  maj_min: "21.1"

recipe:
  name: mlir-split
  version: ${{ version }}

source:
  - url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${{ version | replace(".rc", "-rc") }}.tar.gz
    sha256: 7ba3f2a8d8fda88be18a31d011e8195d3b7f87f9fa92b20c94cba2d7f65b0e3f
    patches:
      # https://reviews.llvm.org/D99470
      - patches/0001-Support-cross-compiling-standalone-MLIR.patch

build:
  number: 0

outputs:
  - package:
      name: mlir
    build:
      script:
        file: ${{ 'install_mlir.bat' if win else 'install_mlir.sh' if unix else '' }}
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - if: build_platform != target_platform
          then: llvmdev 21.1.8.*
      host:
        - ${{ pin_subpackage("libmlir", exact=True) }}
        - llvmdev 21.1.8.*
        - llvm 21.1.8.*
        - zlib
        - if: win
          then: zstd
      run:
        - llvmdev 21.1.8.*
        - if: unix
          then: ${{ pin_subpackage("libmlir" ~ major_version, exact=True) }}
        # we need to do this manually because clang_bootstrap has no run-export
        - if: osx
          then: libcxx >=${{ cxx_compiler_version }}
      ignore_run_exports:
        from_package:
          - if: unix
            then: zlib
    tests:
      - script:
          - if: unix
            then: test -f $PREFIX/lib/libMLIRIR.a
          - if: win
            then: if not exist %LIBRARY_LIB%\MLIRIR.lib exit 1
          - if: unix
            then: test -f $PREFIX/include/mlir-c/Support.h
          - if: win
            then: if not exist %LIBRARY_INC%\mlir-c\Support.h exit 1
          - mlir-tblgen -version
          - if: unix
            then: $PREFIX/bin/mlir-opt -version
          - if: win
            then: if not exist "%LIBRARY_BIN%"\mlir-opt.exe exit 1
          - if: win
            then: mlir-opt -version
  - package:
      name: libmlir${{ major_version }}
    build:
      skip: win
      script:
        file: ${{ 'install_libmlir.sh' if unix else '' }}
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - if: build_platform != target_platform or build_platform != target_platform
          then: llvmdev 21.1.8.*
      host:
        - llvmdev 21.1.8.*
        - llvm 21.1.8.*
      run:
        # we need to do this manually because clang_bootstrap has no run-export
        - if: osx
          then: libcxx >=${{ cxx_compiler_version }}
      run_exports:
        - if: unix
          then: ${{ pin_subpackage("libmlir" ~ major_version, upper_bound="x.x") }}
    tests:
      - script:
          - if: linux
            then: test -f $PREFIX/lib/libMLIR.so.${{ maj_min }}${{ extra }}
          - if: linux
            then: test -f $PREFIX/lib/libmlir_runner_utils.so.${{ maj_min }}${{ extra }}
          - if: linux
            then: test -f $PREFIX/lib/libmlir_c_runner_utils.so.${{ maj_min }}${{ extra }}
          - if: osx
            then: test -f $PREFIX/lib/libMLIR.${{ maj_min }}${{ extra }}.dylib
          - if: osx
            then: test -f $PREFIX/lib/libmlir_runner_utils.${{ maj_min }}${{ extra }}.dylib
          - if: osx
            then: test -f $PREFIX/lib/libmlir_c_runner_utils.${{ maj_min }}${{ extra }}.dylib
          - if: unix
            then: test ! -f $PREFIX/lib/libMLIR$SHLIB_EXT
          - if: unix
            then: test ! -f $PREFIX/lib/libmlir_runner_utils$SHLIB_EXT
          - if: unix
            then: test ! -f $PREFIX/lib/libmlir_c_runner_utils$SHLIB_EXT
          - if: unix
            then: test ! -f $PREFIX/lib/libmlir_c_runner_utils_static.a
  - package:
      name: libmlir
    build:
      script:
        file: ${{ 'install_libmlir.sh' if unix else '' }}
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - if: build_platform != target_platform or build_platform != target_platform
          then: llvmdev 21.1.8.*
      host:
        - llvmdev 21.1.8.*
        - llvm 21.1.8.*
        - if: unix
          then: ${{ pin_subpackage("libmlir" ~ major_version, exact=True) }}
      run:
        - if: unix
          then: ${{ pin_subpackage("libmlir" ~ major_version, exact=True) }}
        # we need to do this manually because clang_bootstrap has no run-export
        - if: osx
          then: libcxx >=${{ cxx_compiler_version }}
      run_exports:
        - if: unix
          then: ${{ pin_subpackage("libmlir" ~ major_version, upper_bound="x.x") }}
    tests:
      - script:
          - if: unix
            then: test -f $PREFIX/lib/libMLIR${SHLIB_EXT}
          - if: win
            then: if exist %LIBRARY_BIN%\libmlir.dll exit 1

about:
  license: Apache-2.0 WITH LLVM-exception
  license_file: mlir/LICENSE.TXT
  summary: Multi-Level IR Compiler Framework
  homepage: http://llvm.org/

extra:
  recipe-maintainers:
    - h-vetinari
    - isuruf
    - kaushikcfd
    - xhochy
  feedstock-name: mlir

