schema_version: 1

context:
  version: "1.9.7"

package:
  name: jsoncpp
  version: ${{ version }}

source:
  url: https://github.com/open-source-parsers/jsoncpp/archive/${{ version }}.tar.gz
  sha256: 830bf352d822d8558e9d0eb19d640d2e38536b4b6699c30a4488da09d5b1df18

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then: make
    - if: unix
      then: pkg-config
    - python
  run_exports:
    - ${{ pin_subpackage('jsoncpp', upper_bound='x.x.x') }}
  host: []

tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - if: unix
        then: test -f "${PREFIX}/include/json/json.h"
      - if: win
        then: if not exist %PREFIX%\\Library\\include\\json\\json.h exit 1
      - if: unix
        then: test -f "${PREFIX}/lib/pkgconfig/jsoncpp.pc"
      - if: unix
        then: test ! -f "${PREFIX}/lib/libjsoncpp.a"
      - if: unix and build_platform == target_platform
        then: python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libjsoncpp${SHLIB_EXT}']"
      - if: win
        then: if not exist %PREFIX%\\Library\\lib\\jsoncpp.lib exit 1
      - cmake-package-check jsoncpp

about:
  license: LicenseRef-Public-Domain OR MIT
  license_file: LICENSE
  summary: A C++ library for interacting with JSON.
  homepage: https://github.com/open-source-parsers/jsoncpp

extra:
  recipe-maintainers:
    - jakirkham
    - stuarteberg
    - marcelotrevisani
    - matthiasdiener

