schema_version: 1

context:
  name: adwaita-icon-theme
  version: "49.0"
  major_version: "49"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/${{ name }}/${{ major_version }}/${{ name }}-${{ version }}.tar.xz
  sha256: 65166461d1b278aa942f59aa8d0fccf1108d71c65f372c6266e172449791755c

build:
  number: 0
  noarch: generic
  merge_build_and_host_envs: false

requirements:
  build:
    # gtk needed for building icon cache, build OK because cache file is platform-independent
    - gtk3
    - meson
    - ninja
    - python
  host:
  # explicitly empty
  run:
    - if: unix
      then: __unix
    - if: win
      then: __win
    - hicolor-icon-theme
    # librsvg needed at runtime for libpixbufloader-svg.so so svgs can be rendered
    - librsvg

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/share/icons/Adwaita/icon-theme.cache
      - if: unix
        then: test -f $PREFIX/share/icons/Adwaita/index.theme
      - if: unix
        then: test -f $PREFIX/share/icons/Adwaita/16x16/devices/audio-headphones.png
      - if: unix
        then: test -f $PREFIX/share/icons/Adwaita/cursors/cross
      - if: unix
        then: test -f $PREFIX/share/icons/Adwaita/cursors/default
      - if: unix
        then: test -f $PREFIX/share/icons/Adwaita/scalable/devices/computer.svg
      - if: win
        then: if not exist %PREFIX%\Library\share\icons\Adwaita\icon-theme.cache exit 1
      - if: win
        then: if not exist %PREFIX%\Library\share\icons\Adwaita\index.theme exit 1
      - if: win
        then: if not exist %PREFIX%\Library\share\icons\Adwaita\16x16\devices\audio-headphones.png  exit 1
      - if: win
        then: if not exist %PREFIX%\Library\share\icons\Adwaita\cursors\crosshair.cur exit 1
      - if: win
        then: if not exist %PREFIX%\Library\share\icons\Adwaita\cursors\default.cur exit 1
      - if: win
        then: if not exist %PREFIX%\Library\share\icons\Adwaita\scalable\devices\computer.svg exit 1

about:
  license: LGPL-3.0-or-later OR CC-BY-SA-3.0
  license_file: COPYING
  summary: The default icon theme used by the GNOME desktop
  description: |
    This package contains the default icon theme used by the GNOME desktop.
    The icons are used in many of the official GNOME applications like eog,
    Evince, system monitor, and many more.
  homepage: https://developer.gnome.org
  repository: https://gitlab.gnome.org/GNOME/adwaita-icon-theme

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj

