context:
  version: 1.0.0

package:
  name: openabe
  version: ${{ version }}

source:
  url: https://github.com/FSSlc/openabe/archive/refs/heads/master.zip
  # path: ../../pkgs/openabe-${{ version }}.zip
  sha256: df1497efeab96d4d13175b6adc7210575b2d8359756279eab4f37036d27b3d3e
  patches:
    - if: linux and x86_64
      then: relic-compile.patch
    - if: linux and aarch64
      then: relic-compile-arm.patch

build:
  number: 0
  dynamic_linking:
    rpaths:
     - lib/openabe

requirements:
  build:
    - ${{ compiler('cxx') }}
    - make
    - cmake
    - m4
    - flex
    - bison
    - gmp
    - wget # for download gtest source
    - unzip # for unzip gtest source
    - bzip2
    - perl >=5

about:
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: The OpenABE library - open source cryptographic library with attribute-based encryption implementations in C/C++.
  description: |
    OpenABE is a cryptographic library that incorporates a variety of attribute-based encryption (ABE) algorithms, 
    industry standard cryptographic functions and tools, and an intuitive application programming interface (API). 
  homepage: https://github.com/zeutro/openabe
  documentation: https://github.com/zeutro/openabe

extra:
  recipe-maintainers:
    - fsslc
