context:
  version: 8.1.3

package:
  name: rtty
  version: ${{ version }}

source:
  url: https://github.com/zhaojh329/rtty/releases/download/v{{ version }}/rtty-{{ version }}.tar.gz
  # path: ../../pkgs/rtty-${{ version }}.tar.gz
  sha256: d31596cb601d88b2cf651ee5497e22000b7a855f80c872ac2b411fc272c83d13
  file_name: rtty-${{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - cmake
    - make
  host:
    - libev
    - openssl
    - libxcrypt

tests:
  - script:
      - if: not win
        then: test -f ${PREFIX}/bin/rtty

about:
  license: MIT
  license_file: LICENSE
  summary: Tool for analyzing includes in C++.
  description: |
    🐛 Access your terminal from anywhere via the web.
  homepage: https://github.com/zhaojh329/rtty
  documentation: https://github.com/zhaojh329/rtty

extra:
  recipe-maintainers:
    - fsslc
