schema_version: 1

context:
  name: zoltan
  version: 3.901
  build: 3
  mpi: mpich
  mpi_prefix: mpi_mpich

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/sandialabs/Zoltan/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 030c22d9f7532d3076e40cba1f03a63b2ee961d8cc9a35149af4a3684922a910
  patches:
    - token-replace.pl.patch

build:
  number: ${{ build }}
  string: ${{ mpi_prefix }}_h${{ hash }}_${{ build }}
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - make
    - if: unix
      then: gnuconfig
  host:
    - ${{ mpi }}
    - perl
  run_exports:
    - ${{ name }} * ${{ mpi_prefix }}_*

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/include/zoltan.h

about:
  license: BSD-3-Clause
  license_file: COPYRIGHT_AND_LICENSE
  summary: Parallel Partitioning, Load Balancing and Data-Management Services
  description: |
    The Zoltan Library provides critical data-management services to a wide range of parallel applications.
  homepage: http://www.cs.sandia.gov/Zoltan/
  repository: https://github.com/sandialabs/Zoltan
  documentation: https://cs.sandia.gov/Zoltan/

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - cekees
    - DavidBrochart
    - rishi9699
    - xylar
    - fsslc
