schema_version: 1

context:
  name: unrar
  version: "0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/unrar-${{ version }}.tar.gz
  sha256: b24447a5b93024be600ef8255668ba23a30f451176577b691559ea1359f7d164

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - libunrar

tests:
  - python:
      imports:
        - unrar
        - unrar.tests
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Wrapper for UnRAR library, ctypes-based.
  license: GPL-3.0-only
  license_file: LICENSE.txt
  homepage: http://github.com/matiasb/python-unrar
  repository: https://github.com/matiasb/python-unrar
  documentation: https://python-unrar.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - kellend-git
    - sshockwave

