#!/bin/bash
set -ex

mkdir -p build && cd build

cmake -GNinja \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_VERBOSE_WINPR_ASSERT=OFF \
  ${CMAKE_ARGS} \
  -DCMAKE_PREFIX_PATH="${PREFIX}" \
  -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DWITH_ALSA=ON \
  -DWITH_PULSE=ON \
  -DWITH_ALSA=ON \
  -DWITH_PULSE=ON \
  -DWITH_CUPS=OFF \
  -DWITH_OPENSSL=ON \
  -DWITH_X11=ON \
  -DWITH_WAYLAND=ON \
  -DWITH_CLIENT_SDL=OFF \
  -DWITH_SERVER=ON \
  -DWITH_SHADOW=ON \
  -DWITH_PROXY=ON \
  -DWITH_KRB5=ON \
  -DWITH_JPEG=ON \
  -DWITH_FFMPEG=OFF \
  -DWITH_DSP_FFMPEG=OFF \
  -DWITH_VIDEO_FFMPEG=OFF \
  -DWITH_SWSCALE=OFF \
  -DWITH_OPENH264=OFF \
  -DWITH_CAIRO=OFF \
  -DWITH_MANPAGES=OFF \
  -DWITH_SAMPLE=OFF \
  -DWITH_JSONC=OFF \
  -DWITH_LIBSYSTEMD=OFF \
  -DWITH_PCSC=OFF \
  -DWITH_FAAC=OFF \
  -DWITH_FAAD2=OFF \
  -DWITH_LAME=OFF \
  -DWITH_OPUS=OFF \
  -DWITH_GSM=OFF \
  -DWITH_SOXR=OFF \
  -DWITH_VAAPI=OFF \
  -DWITH_OPENCL=OFF \
  -DWITH_WEBVIEW=OFF \
  -DWITH_MBEDTLS=OFF \
  -DWITH_AOM=OFF \
  -DWITH_YUV=OFF \
  -DWITH_FUSE=OFF \
  -DCHANNEL_URBDRC=OFF \
  -DBUILD_TESTING=OFF \
  -DBUILD_SHARED_LIBS=ON \
  -DFREERDP_UNIFIED_BUILD=ON \
  $SRC_DIR

ninja -j${CPU_COUNT}
ninja install

# Remove libtool archives
find $PREFIX -name "*.la" -delete
