mpi:
  - nompi
  - mpich  # [unix]

pin_run_as_build:
  mpich: x.x

hdf5_version:
  - 1.10.9

hdf5_sha:
  - f5b77f59b705a755a5a223372d0222c7bc408fe8db6fa8d9d7ecf8bce291b8dd

zip_keys:
  - - hdf5_version
    - hdf5_sha
