#!/bin/bash

cmake \
    -G Ninja \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DREFLECTCPP_BUILD_SHARED=ON \
    -DREFLECTCPP_INSTALL=ON \
    -DREFLECTCPP_BUILD_TESTS=OFF \
    -DREFLECTCPP_BUILD_BENCHMARKS=OFF \
    -DREFLECTCPP_USE_VCPKG=OFF \
    -DREFLECTCPP_USE_BUNDLED_DEPENDENCIES=ON \
    -DREFLECTCPP_YAML=ON \
    $SRC_DIR \
    ${CMAKE_ARGS}

ninja install
