context:
  name: opendev
  version: "0.1.9"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/opendev-to/opendev/releases/download/v${{ version }}/opendev-cli-x86_64-unknown-linux-gnu.tar.xz
      sha256: a64752cd4fa34265c2c777191ee7bec5f9e896d750ea95a3118b25dd332bf524

  - if: linux and aarch64
    then:
      url: https://github.com/opendev-to/opendev/releases/download/v${{ version }}/opendev-cli-aarch64-unknown-linux-gnu.tar.xz
      sha256: 1ebe17046805c3fc8d52258bce9fa5590b797ddd0480bef32c92c01ee8c07061    

  - if: osx and x86_64
    then:
      url: https://github.com/opendev-to/opendev/releases/download/v${{ version }}/opendev-cli-x86_64-apple-darwin.tar.xz
      sha256: c48de7c3191aed5fe7bea93c76657aabf053ac5bd18d34b7e7f69cd60b24ccb0    

  - if: osx and arm64
    then:
      url: https://github.com/opendev-to/opendev/releases/download/v${{ version }}/opendev-cli-aarch64-apple-darwin.tar.xz
      sha256: 6b50c2daf1801e912adda8350a6e7c77f62eb87cd5171729711d1fd1282e29b8    

  - if: win and x86_64
    then:
      url: https://github.com/opendev-to/opendev/releases/download/v${{ version }}/opendev-cli-x86_64-pc-windows-msvc.zip
      sha256: 0d55b270aa70d3bb8ac38c1f10a7e911cf6df2edf2c738e60294925de1a874e9

requirements:
  build: null
  run: null

build:
  number: 0
  script:
    - |
      mkdir -p "${PREFIX}/bin"

      if [[ "${target_platform}" == "linux-64" ]]; then
          mv opendev "${PREFIX}/bin"
          mv runtime "${PREFIX}/bin"

      elif [[ "${target_platform}" == "linux-aarch64" ]]; then
          mv opendev "${PREFIX}/bin"
          mv runtime "${PREFIX}/bin"

      elif [[ "${target_platform}" == "osx-64" ]]; then
          mv opendev "${PREFIX}/bin"

      elif [[ "${target_platform}" == "osx-arm64" ]]; then
          mv opendev "${PREFIX}/bin"

      elif [[ "${target_platform}" == "win-64" ]]; then
          mv opendev* "${PREFIX}/bin"

      fi

      if [[ "${target_platform}" != win-* ]]; then
          chmod +x "${PREFIX}/bin/opendev"
      fi

about:
  homepage: https://github.com/opendev-to/opendev
  repository: https://github.com/opendev-to/opendev
  license: MIT
  license_file: LICENSE
  summary: Open-source AI coding agent for the terminal
  description: |
    OpenDev is a terminal-based AI coding agent.
    This package repackages official upstream binaries
    for all supported conda platforms.


extra:
  recipe-maintainers:
    - FSSlc