schema_version: 1

context:
  name: gast
  version: "0.6.0"
  sha256: 88fc5300d32c7ac6ca7b515310862f71e6fdf2c029bbec7c66c0f5dd47b6b1fb

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
  run_constraints:
    - pythran >=0.12.2

tests:
  - python:
      imports:
        - gast

about:
  license: BSD-3-Clause
  # https://github.com/serge-sans-paille/gast/pull/17
  license_file: LICENSE
  summary: A generic AST to represent Python2 and Python3's Abstract Syntax Tree(AST).
  description: |
    GAST provides a compatibility layer between the AST of various Python
    versions, as produced by ast.parse from the standard ast module.
  homepage: https://github.com/serge-sans-paille/gast
  repository: https://github.com/serge-sans-paille/gast

extra:
  recipe-maintainers:
    - CurtLH
    - martinRenou
    - conda-forge/pythran

