schema_version: 1

context:
  name: omp4py
  version: "0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/omp4py-${{ version }}.tar.gz
  sha256: b4af1988b9adb7fa95e83a9166750abdd3841d4aefc10650e040fb98043dfc5e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0.0

tests:
  - python:
      imports:
        - omp4py
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: An OpenMP Implementation for Python
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/citiususc/omp4py

extra:
  recipe-maintainers:
    - jan-janssen
