{% set name = "mesa-opt" %}
{% set version = "24.2.8" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: construct.yaml
  sha256: 4ba63601771980c6156eb1234d19cf3c7273314f18e907f0e337e5bfc13287ca

build:
  number: 2

requirements:
  build:
    - constructor
  host:

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/
