schema_version: 1

context:
  name: conduit
  version: "0.9.5"
  sha256: d93294efbf0936da5a27941e13486aa1a04a74a59285786a2303eed19a24265a

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/LLNL/conduit/releases/download/v${{ version }}/conduit-v${{ version }}-src-with-blt.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 1
  skip: win and vc<14

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ${{ compiler("fortran") }}
    - if: linux
      then: make
    - cmake
  host:
    - if: mpi != 'nompi'
      then: ${{ mpi }}
    - if: match(python, ">=3.8")
      then: libpython-static
    - python
    - pip
    - numpy
    - openssl
    - hdf5
    - zlib
  run:
    - if: mpi != 'nompi'
      then: ${{ mpi }}
    - python
    - zlib

tests:
  - python:
      imports:
        - conduit
        - conduit.relay
        - conduit.blueprint
      pip_check: false
  - requirements:
      run:
        - numpy
    script:
      - if: osx
        then: test -f $PREFIX/lib/libconduit.dylib
      - if: linux
        then: test -f $PREFIX/lib/libconduit.so
      - if: win
        then: if not exist %PREFIX%\\Library\\lib\\conduit.lib exit 1

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Simplified Data Exchange for HPC Simulations
  description: |
    Conduit is an open source project from Lawrence Livermore National
    Laboratory that provides an intuitive model for describing hierarchical
    scientific data in C++, C, Fortran, and Python. It is used for data\
    coupling between packages in-core, serialization, and I/O tasks.
  homepage: https://github.com/LLNL/conduit
  repository: https://github.com/LLNL/conduit
  documentation: https://software.llnl.gov/conduit

extra:
  recipe-maintainers:
    - cyrush

