schema_version: 1

context:
  name: popt
  version: "1.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: http://ftp.rpm.org/mirror/${{ name|lower }}/${{ name|lower }}-${{ version }}.tar.gz
    sha256: e728ed296fe9f069a0e005003c3d6b2dde3d9cad453422a10d6558616d304cc8
    patches:
      - if: osx
        then: 0001-remove-tests-58-and-59.patch
      - 0002-added-sanity-autotest.patch

build:
  number: 2002
  skip: win

requirements:
  build:
    - if: unix
      then: gnuconfig
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - libiconv
    - perl
    - make
  run:
    - libiconv
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x') }}

tests:
  - script:
      - test -f $PREFIX/include/popt.h
      - test -f $PREFIX/lib/libpopt.a
      - if: linux
        then: test -f $PREFIX/lib/libpopt.so
      - if: osx
        then: test -f $PREFIX/lib/libpopt.dylib

about:
  license: MIT
  license_file: COPYING
  summary: Popt is a C library for parsing command line parameters.
  homepage: http://rpm5.org/

extra:
  recipe-maintainers:
    - notestaff
    - sodre

