context:
  version: "1.9.2"

package:
  name: libfind
  version: ${{ version }}

source:
  url: https://github.com/FSSlc/libfind/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7b6cede89d2b627a491f08a9af5bdd3b27804ea2c4562d5b717e6307b1432f00

build:
  number: 0
  noarch: generic
  script:
    - make DEST=${PREFIX} install

requirements:
  build:
    - sed
    - make
  run:
    - cmake >=3.12

about:
  homepage: https://github.com/FSSlc/libfind
  repository: https://github.com/FSSlc/libfind
  license: MIT
  summary: A collection of cmake modules used in SCNS.

extra:
  recipe-maintainers:
    - fsslc
