schema_version: 1

context:
  version: "7.3.0"

package:
  name: redis-py
  version: ${{ version }}

source:
  url: https://github.com/redis/redis-py/archive/v${{ version }}.tar.gz
  sha256: 36ba3135eb2bcf6fdebccecb2614507a687ab9ec2fc507fdcd87c822616a28c1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - async-timeout >=4.0.3

tests:
  - python:
      imports:
        - redis
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: Python client for Redis key-value store
  description: |
    The Python interface to the Redis key-value store. Requires a running
    Redis server.
  homepage: https://github.com/redis/redis-py/
  repository: https://github.com/redis/redis-py/
  documentation: https://pypi.python.org/pypi/redis

extra:
  recipe-maintainers:
    - rxm7706
    - kwilcox
    - daf

