cross_target_platform:
  - linux-64                            # [linux]
rust_arch:
  - x86_64-unknown-linux-gnu            # [linux]
rust_arch_env_build:
  - X86_64_UNKNOWN_LINUX_GNU            # [linux64]
rust_arch_env:
  - X86_64_UNKNOWN_LINUX_GNU            # [linux]
rust_default_cc_build:
  - x86_64-scns-linux-gnu-cc           # [linux64]
rust_default_cc:
  - x86_64-scns-linux-gnu-cc           # [linux]
# This should be max(build_platform_ver, cross_target_platform_ver)
MACOSX_SDK_VERSION:
  - 0                                   # [linux]
MACOSX_DEPLOYMENT_TARGET:
  - 0                                   # [linux]

# Don't call it c_stdlib_version as otherwise, we will get conflicts with cdt_name zipping
# This is also the version for the target, not the host (for cross-compilers)
target_c_stdlib_version:
  - '2.17'                              # [linux]

version:
  - 1.94.0  # [linux]

zip_keys:
  - - cross_target_platform
    - rust_arch
    - rust_arch_env
    - rust_default_cc
    - MACOSX_SDK_VERSION
    - MACOSX_DEPLOYMENT_TARGET
    - target_c_stdlib_version
    - version
