name: Build all packages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-22.04 }
          - { target: linux-aarch64, os: ubuntu-22.04-arm }
      fail-fast: false

    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: kohlerdominik/docker-run-action@v2.1.0
        with:
          image: ghcr.io/fsslc/pixi:latest
          volumes: ${{ github.workspace }}:${{ github.workspace }}
          shell: /bin/bash
          workdir: ${{ github.workspace }}
          run: |
            if [ -f only-meta.txt ]; then
              while IFS= read -r pkgname; do
                [ -z "$pkgname" ] && continue
                conda build --croot ./output/ -m ./conda_build_config.yaml \
                  --skip-existing -c https://prefix.dev/scns todo/"$pkgname"
              done < only-meta.txt
            fi

            count=$(find ./output/ -type f -name '*.conda' -print0 | grep -zc . || true)
            if (( count > 0 )); then
              for file in output/**/*.conda; do
                rattler-build upload prefix -c scns -a ${{ secrets.PREFIX_DEV_TOKEN }} --skip-existing "$file"
              done
            else
              echo "nothing to do"
            fi

      - uses: kohlerdominik/docker-run-action@v2.1.0
        with:
          image: ghcr.io/fsslc/pixi:latest
          volumes: ${{ github.workspace }}:${{ github.workspace }}
          shell: /bin/bash
          workdir: ${{ github.workspace }}
          run: |
            rattler-build build --continue-on-failure --experimental \
              -m ./conda_build_config.yaml --skip-existing=all \
              --target-platform=${{ matrix.target }} -c https://prefix.dev/scns \
              --recipe-dir ./todo

            count=$(find ./output/ -type f -name '*.conda' -print0 | grep -zc . || true)
            if (( count > 0 )); then
              for file in output/**/*.conda; do
                rattler-build upload prefix -c scns -a ${{ secrets.PREFIX_DEV_TOKEN }} --skip-existing "$file"
              done
            else
              echo "nothing to do"
            fi
