name: Build all packages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-20.04 }
          - { target: linux-aarch64, os: ubuntu-22.04-arm }
      fail-fast: false

    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.62.2
          cache: false
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

      - uses: kohlerdominik/docker-run-action@v2.0.0
        with:
          image: ghcr.io/fsslc/pixi:latest
          volumes: ${{ github.workspace }}:${{ github.workspace }}
          shell: /bin/bash
          workdir: ${{ github.workspace }}
          run: |
            rattler-build build --recipe-dir ./recipes \
              -m ./conda_build_config.yaml --skip-existing=all \
              --target-platform=${{ matrix.target }} \
              -c https://prefix.dev/scns -c https://prefix.dev/lcforge
            for file in output/**/*.conda; do
              rattler-build upload prefix -c lcforge -a ${{ secrets.PREFIX_DEV_TOKEN }} --skip-existing "$file"
            done
